name: Manual Build Android

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish the build (e.g., v2.0.1)'
        required: true
      godot_version:
        description: 'Godot version to be builded (e.g., 3.5)'
        required: true

jobs:
  android-template:
    name: Compiling Gradle (Android)
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        RELEASE_VERSIONS: ["standard", "mono"]

    steps:
    - uses: actions/checkout@v2

    - name: Verify current inputs godot_version
      run: |
        CURRENT_GODOT_VERSION=${{ github.event.inputs.godot_version }}
        if [ ${#CURRENT_GODOT_VERSION} -eq 1 ]; then CURRENT_GODOT_VERSION="${CURRENT_GODOT_VERSION}.0"; fi
        echo "CURRENT_GODOT_VERSION=${CURRENT_GODOT_VERSION}" >> $GITHUB_ENV

    - name: Download and prepare the Stable Godot .AAR LIB
      run: | 
        cd godot-lib 
        GODOT_AAR_LIB="godot-lib.aar"
        if [ ${{matrix.RELEASE_VERSIONS}} = standard ]; then 
          GODOT_AAR_FILENAME="godot-lib.${{env.CURRENT_GODOT_VERSION}}.stable.release.aar"
          FULL_PATHNAME_DOWNLOAD_GODOT_AAR="https://downloads.tuxfamily.org/godotengine/${{env.CURRENT_GODOT_VERSION}}/${GODOT_AAR_FILENAME}"
        elif [ ${{matrix.RELEASE_VERSIONS}} = mono ]; then 
          GODOT_AAR_FILENAME="godot-lib.${{env.CURRENT_GODOT_VERSION}}.stable.mono.release.aar"
          FULL_PATHNAME_DOWNLOAD_GODOT_AAR="https://downloads.tuxfamily.org/godotengine/${{env.CURRENT_GODOT_VERSION}}/mono/${GODOT_AAR_FILENAME}"
        fi

        #get file on Godot's server and rename
        wget $FULL_PATHNAME_DOWNLOAD_GODOT_AAR
        mv $GODOT_AAR_FILENAME $GODOT_AAR_LIB
    
    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        
    - name: Build with Gradle
      run: | 
        ./gradlew build

    - name: Compress the binaries
      run: |
        mv admob/AdMob.gdap admob/build/outputs/aar/
        zip -j android-${{matrix.RELEASE_VERSIONS}}-template-v${{env.CURRENT_GODOT_VERSION}}.zip admob/build/outputs/aar/*

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-${{matrix.RELEASE_VERSIONS}}-template-v${{env.CURRENT_GODOT_VERSION}}.zip
        path: android-${{matrix.RELEASE_VERSIONS}}-template-v${{env.CURRENT_GODOT_VERSION}}.zip

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: android-${{matrix.RELEASE_VERSIONS}}-template-v${{env.CURRENT_GODOT_VERSION}}.zip
        tag: ${{ github.event.inputs.tag }}
        overwrite: true
