name: Manual Build Android

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish the build (e.g., v2.0.1)'
        required: true
      godot_version:
        description: 'Godot version to be builded (e.g., 3.5)'
        required: true

jobs:
  android-template:
    name: Compiling Gradle (Android)
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        RELEASE_VERSIONS: ["standard", "mono"]

    steps:
    - uses: actions/checkout@v2
    
    - name: Build Android Action
      id: build-android
      uses: Poing-Studios/godot-android-action@master
      with:
        godot_version: ${{ github.event.inputs.godot_version }}
        release_version: ${{matrix.RELEASE_VERSIONS}}
        project_path: admob
        gdap_file_path: admob/AdMob.gdap

    - uses: actions/download-artifact@v3
      with:
        name: ${{ steps.build-android.outputs.artifact_name }}
        path: artifacts_output

    - name: Compress the artifact output
      run: |
        compressed_file_output=android-${{matrix.RELEASE_VERSIONS}}-template-v${{env.CURRENT_GODOT_VERSION}}.zip
        zip -r $compressed_file_output .
        ls -R
      working-directory: artifacts_output
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: artifacts_output/$compressed_file_output
        tag: ${{ github.event.inputs.tag }}
        overwrite: true
